[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[functions."trigger-collect"]
  schedule = "20 1 * * *"

[[redirects]]
  from = "/*"
  to = "/maintenance.html"
  status = 200
